'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AspNetRoles
    Public Property Id As String
    Public Property Name As String
    Public Property Description As String
    Public Property Discriminator As String

    Public Overridable Property AspNetUsers As ICollection(Of AspNetUsers) = New HashSet(Of AspNetUsers)

End Class
