'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class AtlasBlogEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AtlasBlogEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property BlogKathgoriesTable() As DbSet(Of BlogKathgoriesTable)
    Public Overridable Property BlogPostandKathgoriaTable() As DbSet(Of BlogPostandKathgoriaTable)
    Public Overridable Property BlogPostsTable() As DbSet(Of BlogPostsTable)
    Public Overridable Property BlogProgramma() As DbSet(Of BlogProgramma)
    Public Overridable Property BlogNewPlayer() As DbSet(Of BlogNewPlayer)
    Public Overridable Property BlogNewTeam() As DbSet(Of BlogNewTeam)

    Public Overridable Function GetPreviousandNextpostid(currentpostid As Nullable(Of Integer), k As String, ak As Nullable(Of Integer)) As ObjectResult(Of GetPreviousandNextpostid_Result)
        Dim currentpostidParameter As ObjectParameter = If(currentpostid.HasValue, New ObjectParameter("currentpostid", currentpostid), New ObjectParameter("currentpostid", GetType(Integer)))

        Dim kParameter As ObjectParameter = If(k IsNot Nothing, New ObjectParameter("k", k), New ObjectParameter("k", GetType(String)))

        Dim akParameter As ObjectParameter = If(ak.HasValue, New ObjectParameter("ak", ak), New ObjectParameter("ak", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetPreviousandNextpostid_Result)("GetPreviousandNextpostid", currentpostidParameter, kParameter, akParameter)
    End Function

End Class
