'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class AtlasBlogEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AtlasBlogEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AspNetRoles() As DbSet(Of AspNetRoles)
    Public Overridable Property AspNetUserClaims() As DbSet(Of AspNetUserClaims)
    Public Overridable Property AspNetUserLogins() As DbSet(Of AspNetUserLogins)
    Public Overridable Property AspNetUsers() As DbSet(Of AspNetUsers)
    Public Overridable Property BlogKathgoriesTable() As DbSet(Of BlogKathgoriesTable)
    Public Overridable Property BlogPostandKathgoriaTable() As DbSet(Of BlogPostandKathgoriaTable)
    Public Overridable Property BlogPostsTable() As DbSet(Of BlogPostsTable)
    Public Overridable Property BlogProgramma() As DbSet(Of BlogProgramma)

End Class
