'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class AtlasStatisticsEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AtlasStatisticsEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property DiorganwshTable() As DbSet(Of DiorganwshTable)
    Public Overridable Property GamesTable() As DbSet(Of GamesTable)
    Public Overridable Property GipedaTable() As DbSet(Of GipedaTable)
    Public Overridable Property KathgoriesTable() As DbSet(Of KathgoriesTable)
    Public Overridable Property OmilosTable() As DbSet(Of OmilosTable)
    Public Overridable Property PlayersStatisticsTable() As DbSet(Of PlayersStatisticsTable)
    Public Overridable Property PlayersTable() As DbSet(Of PlayersTable)
    Public Overridable Property SeasonTable() As DbSet(Of SeasonTable)
    Public Overridable Property TeamsandKathgoriesTable() As DbSet(Of TeamsandKathgoriesTable)
    Public Overridable Property TeamsandPlayersTable() As DbSet(Of TeamsandPlayersTable)
    Public Overridable Property TeamsStatisticsTable() As DbSet(Of TeamsStatisticsTable)
    Public Overridable Property TeamsTable() As DbSet(Of TeamsTable)

    Public Overridable Function getallteamsrankings(season As Nullable(Of Integer), diorganwsh As Nullable(Of Integer), omilos As Nullable(Of Integer), kathgoria As Nullable(Of Integer)) As ObjectResult(Of getallteamsrankings_Result)
        Dim seasonParameter As ObjectParameter = If(season.HasValue, New ObjectParameter("season", season), New ObjectParameter("season", GetType(Integer)))

        Dim diorganwshParameter As ObjectParameter = If(diorganwsh.HasValue, New ObjectParameter("diorganwsh", diorganwsh), New ObjectParameter("diorganwsh", GetType(Integer)))

        Dim omilosParameter As ObjectParameter = If(omilos.HasValue, New ObjectParameter("omilos", omilos), New ObjectParameter("omilos", GetType(Integer)))

        Dim kathgoriaParameter As ObjectParameter = If(kathgoria.HasValue, New ObjectParameter("kathgoria", kathgoria), New ObjectParameter("kathgoria", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of getallteamsrankings_Result)("getallteamsrankings", seasonParameter, diorganwshParameter, omilosParameter, kathgoriaParameter)
    End Function

    Public Overridable Function GetWeeklyReportStat1All(omid As Nullable(Of Integer), kid As Nullable(Of Integer)) As ObjectResult(Of GetWeeklyReportStat1All_Result)
        Dim omidParameter As ObjectParameter = If(omid.HasValue, New ObjectParameter("omid", omid), New ObjectParameter("omid", GetType(Integer)))

        Dim kidParameter As ObjectParameter = If(kid.HasValue, New ObjectParameter("kid", kid), New ObjectParameter("kid", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetWeeklyReportStat1All_Result)("GetWeeklyReportStat1All", omidParameter, kidParameter)
    End Function

    Public Overridable Function GetWeeklyReportStat2All(omid As Nullable(Of Integer), kid As Nullable(Of Integer)) As ObjectResult(Of GetWeeklyReportStat2All_Result)
        Dim omidParameter As ObjectParameter = If(omid.HasValue, New ObjectParameter("omid", omid), New ObjectParameter("omid", GetType(Integer)))

        Dim kidParameter As ObjectParameter = If(kid.HasValue, New ObjectParameter("kid", kid), New ObjectParameter("kid", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetWeeklyReportStat2All_Result)("GetWeeklyReportStat2All", omidParameter, kidParameter)
    End Function

    Public Overridable Function GetWeeklyReportStat3All(omid As Nullable(Of Integer), kid As Nullable(Of Integer)) As ObjectResult(Of GetWeeklyReportStat3All_Result)
        Dim omidParameter As ObjectParameter = If(omid.HasValue, New ObjectParameter("omid", omid), New ObjectParameter("omid", GetType(Integer)))

        Dim kidParameter As ObjectParameter = If(kid.HasValue, New ObjectParameter("kid", kid), New ObjectParameter("kid", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetWeeklyReportStat3All_Result)("GetWeeklyReportStat3All", omidParameter, kidParameter)
    End Function

    Public Overridable Function GetWeeklyReportStat4All(omid As Nullable(Of Integer), kid As Nullable(Of Integer)) As ObjectResult(Of GetWeeklyReportStat4All_Result)
        Dim omidParameter As ObjectParameter = If(omid.HasValue, New ObjectParameter("omid", omid), New ObjectParameter("omid", GetType(Integer)))

        Dim kidParameter As ObjectParameter = If(kid.HasValue, New ObjectParameter("kid", kid), New ObjectParameter("kid", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetWeeklyReportStat4All_Result)("GetWeeklyReportStat4All", omidParameter, kidParameter)
    End Function

    Public Overridable Function GetWeeklyReportStat5All(omid As Nullable(Of Integer), kid As Nullable(Of Integer)) As ObjectResult(Of GetWeeklyReportStat5All_Result)
        Dim omidParameter As ObjectParameter = If(omid.HasValue, New ObjectParameter("omid", omid), New ObjectParameter("omid", GetType(Integer)))

        Dim kidParameter As ObjectParameter = If(kid.HasValue, New ObjectParameter("kid", kid), New ObjectParameter("kid", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetWeeklyReportStat5All_Result)("GetWeeklyReportStat5All", omidParameter, kidParameter)
    End Function

End Class
