'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BlogPostsTable
    Public Property Id As Integer
    Public Property Activepost As Boolean
    Public Property PostTitle As String
    Public Property PostSummary As String
    Public Property PostBody As String
    Public Property PostPhoto As Byte()
    Public Property Youtubelink As String
    Public Property Statslink As String
    Public Property CreationDate As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property EditDate As Nullable(Of Date)
    Public Property EditBy As String

End Class
