'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BlogNewTeam
    Public Property Id As Integer
    Public Property teamname As String
    Public Property teamemail As String
    Public Property teamphone As String
    Public Property teamroster As Byte()
    Public Property CreationDate As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property EditDate As Nullable(Of Date)
    Public Property EditBy As String
    Public Property teamleadername As String
    Public Property teamrosterext As String

End Class
