'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BlogPostandKathgoriaTable
    Public Property Id As Integer
    Public Property AtlasKathgoriaId As Nullable(Of Integer)
    Public Property IsKathgoria As Boolean
    Public Property IsYpokathgoria As Boolean
    Public Property IsAtlasOmilos As Boolean
    Public Property IsAtlasKathgoria As Boolean
    Public Property PostId As Integer
    Public Property CreationDate As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property EditDate As Nullable(Of Date)
    Public Property EditBy As String
    Public Property KathgoriaId As Nullable(Of Integer)

End Class
