'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GamesTable
    Public Property Id As Integer
    Public Property Gamename As String
    Public Property CreationDate As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property EditDate As Nullable(Of Date)
    Public Property EditBy As String
    Public Property Gamestadium As String
    Public Property Gamedate As Nullable(Of Date)
    Public Property Seasonid As Nullable(Of Integer)
    Public Property Diorganwshid As Nullable(Of Integer)
    Public Property Omilosid As Nullable(Of Integer)
    Public Property Kathgoriaid As Nullable(Of Integer)
    Public Property Agwnistiki As String

End Class
