'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class KathgoriesTable
    Public Property Id As Integer
    Public Property Omilosid As Integer
    Public Property KathgoriaName As String
    Public Property ActiveKathgoria As Boolean
    Public Property CreationDate As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property EditDate As Nullable(Of Date)
    Public Property EditBy As String
    Public Property DiataksiPlayoffId As Nullable(Of Integer)
    Public Property DiataksiCupId As Nullable(Of Integer)

End Class
