'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PlayersStatisticsTable
    Public Property Id As Integer
    Public Property CreationDate As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property EditDate As Nullable(Of Date)
    Public Property EditBy As String
    Public Property Playerid As Integer
    Public Property Gameid As Integer
    Public Property pts2in As Nullable(Of Integer)
    Public Property pts2out As Nullable(Of Integer)
    Public Property pts3in As Nullable(Of Integer)
    Public Property pts3out As Nullable(Of Integer)
    Public Property ptstotal As Nullable(Of Integer)
    Public Property pts1in As Nullable(Of Integer)
    Public Property pts1out As Nullable(Of Integer)
    Public Property assists As Nullable(Of Integer)
    Public Property steals As Nullable(Of Integer)
    Public Property turnovers As Nullable(Of Integer)
    Public Property rebounds As Nullable(Of Integer)
    Public Property defrebounds As Nullable(Of Integer)
    Public Property offrebounds As Nullable(Of Integer)
    Public Property faouls As Nullable(Of Integer)
    Public Property blocks As Nullable(Of Integer)
    Public Property teamstatisticsid As Nullable(Of Integer)
    Public Property totaltime As Nullable(Of Integer)
    Public Property tendex As Nullable(Of Double)

End Class
