'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PlayersTable
    Public Property Id As Integer
    Public Property FirstName As String
    Public Property LastName As String
    Public Property Fanela As Nullable(Of Integer)
    Public Property ActivePlayer As Boolean
    Public Property CreationDate As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property EditDate As Nullable(Of Date)
    Public Property EditBy As String
    Public Property RegistrationDate As Nullable(Of Date)
    Public Property FatherName As String
    Public Property BirthDate As Nullable(Of Date)
    Public Property NumberID As String
    Public Property Nationality As String
    Public Property PlayerPhoto As Byte()
    Public Property resizeflag As Nullable(Of Integer)

End Class
