'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ValidationMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.ValidationMessages", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Το πεδίο {0} πρέπει να είναι ημερομηνία..
        '''</summary>
        Friend Shared ReadOnly Property FieldMustBeDate() As String
            Get
                Return ResourceManager.GetString("FieldMustBeDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Το πεδίο {0} πρέπει να είναι αριθμός..
        '''</summary>
        Friend Shared ReadOnly Property FieldMustBeNumeric() As String
            Get
                Return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Η {0} πρέπει να είναι τουλάχιστον {1} χαρακτήρες..
        '''</summary>
        Friend Shared ReadOnly Property MinLengthMsgF() As String
            Get
                Return ResourceManager.GetString("MinLengthMsgF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ο {0} πρέπει να είναι τουλάχιστον {1} χαρακτήρες..
        '''</summary>
        Friend Shared ReadOnly Property MinLengthMsgM() As String
            Get
                Return ResourceManager.GetString("MinLengthMsgM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To {0} πρέπει να είναι τουλάχιστον {1} χαρακτήρες..
        '''</summary>
        Friend Shared ReadOnly Property MinLengthMsgN() As String
            Get
                Return ResourceManager.GetString("MinLengthMsgN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Η τιμή &apos;{0}&apos; δεν είναι αποδεκτή για το πεδίο {1}..
        '''</summary>
        Friend Shared ReadOnly Property PropertyValueInvalid() As String
            Get
                Return ResourceManager.GetString("PropertyValueInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Το πεδίο {0} δεν μπορεί να είναι κενό..
        '''</summary>
        Friend Shared ReadOnly Property PropertyValueRequired() As String
            Get
                Return ResourceManager.GetString("PropertyValueRequired", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
